import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 20,
        backgroundColor: "#f9fafb", 
    },
    avatarWrapper: {
        width: 160,
        height: 160,
        borderRadius: 80,
        padding: 4,
        backgroundColor: "linear-gradient(45deg, #2563eb, #9333ea)",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 20,
        elevation: 6,
    },
    avatar: {
        width: 150,
        height: 150,
        borderRadius: 75,
        borderWidth: 3,
        borderColor: "#fff",
    },
    name: {
        fontSize: 28,
        fontWeight: "bold",
        color: "#1e293b",
    },
    subtitle: {
        fontSize: 16,
        color: "#475569",
        marginBottom: 28,
    },
    linksContainer: {
        width: "100%",
        marginBottom: 40,
    },
    linkButton: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        backgroundColor: "#fff",
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 12,
        marginVertical: 6,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    linkText: {
        fontSize: 18,
        fontWeight: "500",
        color: "#1e293b",
    },
    primaryButton: {
        backgroundColor: "#2563eb",
        paddingVertical: 16,
        paddingHorizontal: 40,
        borderRadius: 14,
        shadowColor: "#2563eb",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 5,
    },
    primaryButtonText: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "600",
        letterSpacing: 0.5,
    },
});
